server:
  port: 8080


spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://liaofushen.xyz:3306/mall_db
      username: remote
      password: 560@lfs

mybatis:
  type-aliases-package: com.lfs.mall.domain
  mapper-locations: classpath:mapper/*.xml
