server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://liaofushen.xyz:3306?useUnicode=true&characterEncoding=UTF-8
      username: remote
      password: 560@lfs

mybatis:
  type-aliases-package: com.lfs.mall.domain
  mapper-locations: classpath:mapper/*.xml


